export const ENVOY = {
  slug: 'envoy',
  nameKey: 'Envoy',
  compendiumUuid: 'Compendium.sf2e-anachronism.classes.Item.wu88dOKl86DTo427',
  keyAbility: ['cha'],
  hp: 8,

  featSchedule: {
    class: [1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    skill: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    general: [3, 7, 11, 15, 19],
    ancestry: [5, 9, 13, 17],
  },
  skillIncreaseSchedule: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
  abilityBoostSchedule: [5, 10, 15, 20],

  classFeatures: [
    { level: 3, name: 'Adaptive Talent', key: 'adaptive-talent' },
    { level: 3, name: 'Wise to the Game', key: 'wise-to-the-game' },
    { level: 5, name: 'Improvised Mastery', key: 'improvised-mastery' },
    { level: 5, name: 'Perception Expertise', key: 'perception-expertise' },
    { level: 5, name: 'Weapon Expertise', key: 'weapon-expertise' },
    { level: 7, name: 'Fortitude Expertise', key: 'fortitude-expertise' },
    { level: 7, name: "Leader's Confidence", key: 'leader-s-confidence' },
    { level: 7, name: 'Weapon Specialization', key: 'weapon-specialization' },
    { level: 9, name: 'Envoy Expertise', key: 'envoy-expertise' },
    { level: 9, name: 'Hidden Agenda', key: 'hidden-agenda' },
    { level: 11, name: 'Perception Mastery', key: 'perception-mastery' },
    { level: 11, name: 'Resolve', key: 'resolve' },
    { level: 11, name: 'Savvy Improviser', key: 'savvy-improviser' },
    { level: 13, name: 'Light Armor Expertise', key: 'light-armor-expertise' },
    { level: 13, name: 'Tactician', key: 'tactician' },
    { level: 13, name: 'Weapon Mastery', key: 'weapon-mastery' },
    { level: 15, name: 'Greater Weapon Specialization', key: 'greater-weapon-specialization' },
    { level: 15, name: 'Legendary Improvisation', key: 'legendary-improvisation' },
    { level: 15, name: 'Reflex Mastery', key: 'reflex-mastery' },
    { level: 17, name: 'Greater Resolve', key: 'greater-resolve' },
    { level: 17, name: 'Incredible Senses', key: 'incredible-senses' },
    { level: 17, name: 'Inscrutable', key: 'inscrutable' },
    { level: 19, name: 'Light Armor Mastery', key: 'light-armor-mastery' },
    { level: 19, name: 'Silver Tongue', key: 'silver-tongue' },
  ],

  spellcasting: null,
};
